name: Deploy to Hugging Face Space

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install huggingface_hub
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Push to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'PY'
          import os, sys
          from huggingface_hub import HfApi, HfHubHTTPError
          api = HfApi()
          SPACE_ID = "nehabathuri/Resume-Comparator"
          try:
              api.upload_folder(
                  repo_id=SPACE_ID,
                  repo_type="space",
                  folder_path=".",
                  path_in_repo=".",
                  commit_message="CI: deploy from GitHub",
                  token=os.environ["HF_TOKEN"],
              )
              print("✅ Upload complete")
          except HfHubHTTPError as e:
              print("❌ HfHubHTTPError:", e, file=sys.stderr); raise
          except Exception as e:
              print("❌ Unexpected error:", e, file=sys.stderr); raise
          PY
