name: Deploy to Hugging Face Space
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }

      - run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Diagnose token & repo access
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'PY'
          import os, sys, json, tempfile, pathlib
          from huggingface_hub import HfApi, HfHubHTTPError
          api = HfApi()
          token = os.environ.get("HF_TOKEN")
          space_id = "nehabathuri/Resume-Comparator"
          print("== whoami ==")
          try:
              print(api.whoami(token=token))
          except Exception as e:
              print("ERR whoami:", e); sys.exit(2)

          print("\n== list_repo_files ==")
          try:
              files = api.list_repo_files(space_id, repo_type="space", token=token)
              print("OK files sample:", files[:10])
          except Exception as e:
              print("ERR list_repo_files:", e); sys.exit(3)

          print("\n== try upload tiny marker file ==")
          try:
              with tempfile.TemporaryDirectory() as d:
                  p = pathlib.Path(d, "ci-marker.txt"); p.write_text("hello from CI")
                  api.upload_file(
                      path_or_fileobj=str(p),
                      path_in_repo="ci-marker.txt",
                      repo_id=space_id,
                      repo_type="space",
                      commit_message="CI: marker",
                      token=token,
                  )
              print("OK tiny upload")
          except HfHubHTTPError as e:
              print("ERR upload_file (permission?):", e); sys.exit(4)
          except Exception as e:
              print("ERR upload_file (other):", e); sys.exit(5)
          PY

      - name: Upload full project
        if: ${{ success() }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'PY'
          import os
          from huggingface_hub import HfApi
          api = HfApi()
          api.upload_folder(
              repo_id="nehabathuri/Resume-Comparator",
              repo_type="space",
              folder_path=".",
              path_in_repo=".",
              commit_message="CI: deploy from GitHub",
              token=os.environ["HF_TOKEN"],
          )
          print("✅ Upload complete")
          PY
